# Generated by Django 5.1.2 on 2024-11-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_supplier_tblproducts_supplierid'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CategoryDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryImage',
            field=models.ImageField(upload_to='CategoryImages/'),
        ),
        migrations.AlterField(
            model_name='tblproducts',
            name='productImage',
            field=models.ImageField(upload_to='ProductImages/'),
        ),
    ]
