# Generated by Django 5.1.2 on 2024-12-09 11:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_category_categorydate_alter_category_categoryimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=200, null=True)),
                ('clientImage', models.ImageField(upload_to='pics')),
                ('clientDescription', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
    ]
