# Generated by Django 5.1.2 on 2025-01-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tblfooter_tblslides_tblsocialmedia_tblsubtopmenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblproducts',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tblproducts',
            name='rating',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
