# Generated by Django 5.1.2 on 2025-01-25 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tblproducts_description_tblproducts_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblProductCarts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200, null=True)),
                ('quantity', models.CharField(max_length=200, null=True)),
                ('productImage', models.ImageField(upload_to='ProductImages/')),
                ('productDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('productId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tblproducts')),
            ],
        ),
    ]
