# Generated by Django 5.1.2 on 2025-01-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_tblproductcarts_priceout'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200, null=True)),
                ('Country', models.CharField(max_length=200, null=True)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('BankAccount', models.CharField(max_length=200, null=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Phone', models.CharField(max_length=200, null=True)),
                ('Email', models.EmailField(max_length=200, null=True)),
                ('Remark', models.TextField(null=True)),
            ],
        ),
    ]
