# Generated by Django 5.1.2 on 2025-01-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_tbltransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltransactions',
            name='Amount',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tbltransactions',
            name='Email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
