# Generated by Django 5.1.2 on 2025-01-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_tbltransactions_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblproductcarts',
            name='UserId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tbltransactions',
            name='UserId',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
