# Generated by Django 5.1.5 on 2025-02-01 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_tblproductcarts_userid_tbltransactions_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productDiscountName', models.CharField(max_length=200, null=True)),
                ('productDiscountDateFrom', models.DateTimeField(auto_now_add=True, null=True)),
                ('productDiscountDateTo', models.DateTimeField(auto_now_add=True, null=True)),
                ('productDiscountPercentage', models.CharField(max_length=200, null=True)),
                ('productDiscountCategory', models.CharField(max_length=200, null=True)),
                ('productPriceBeforeDiscount', models.CharField(max_length=200, null=True)),
                ('productPriceAfterDiscount', models.CharField(max_length=200, null=True)),
                ('productDiscountID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tblproducts')),
            ],
        ),
    ]
