# Generated by Django 5.1.5 on 2025-02-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_tblproductdiscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblproductdiscount',
            name='productDiscountName',
        ),
    ]
