# Generated by Django 5.1.5 on 2025-02-02 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_tblproductdiscount_productdiscountname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblproductdiscount',
            name='productDiscountCategory',
        ),
        migrations.RemoveField(
            model_name='tblproductdiscount',
            name='productPriceAfterDiscount',
        ),
        migrations.RemoveField(
            model_name='tblproductdiscount',
            name='productPriceBeforeDiscount',
        ),
    ]
